heroku/x

- redis/redis.go
Recent version of redigo have a ``DialURL``, which allow us to get rid of ``ParseURL``.
> Recent version of redigo have a DialURL

- go-kit/metrics/provider/discard/discard.go
Need this for any app which does dependency injection on providers. I figure it's better to to have it here.
> Add discard provider

- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
We're currently getting intermittent errors. The weird part is they look like these:
```
<html> <head><title>400 Bad Request</title></head> <body bgcolor="white"> <center><h1>400 Bad Request</h1></center> <hr><center>awselb/2.0</center> </body> </html> 
```
It definitely seems non-retriable, but given the fact that we only get this intermittently suggests to me they're some weird shenanigans that can be retried.
This PR is a quick stab on retries. Tests to come if we even then it's worth it.
> Do retries on error

- go-kit/metrics/provider.go
- go-kit/metrics/provider/discard/discard.go
- go-kit/metrics/provider/librato/doc.go
- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/report.go
> go-kit/metrics: cleanup, add documentation

- Gopkg.lock
- hmiddleware/cors.go
- hmiddleware/disable_keepalive.go
- hmiddleware/disable_keepalive_test.go
- hmiddleware/doc.go
- hmiddleware/example_test.go
- hmiddleware/tls.go
- hmiddleware/tls_test.go
- vendor/github.com/go-chi/chi/.gitignore
- vendor/github.com/go-chi/chi/.travis.yml
- vendor/github.com/go-chi/chi/CHANGELOG.md
- vendor/github.com/go-chi/chi/CONTRIBUTING.md
- vendor/github.com/go-chi/chi/LICENSE
- vendor/github.com/go-chi/chi/README.md
- vendor/github.com/go-chi/chi/chain.go
- vendor/github.com/go-chi/chi/chi.go
- vendor/github.com/go-chi/chi/context.go
- vendor/github.com/go-chi/chi/mux.go
- vendor/github.com/go-chi/chi/tree.go
> hmiddleware: Add documentation, examples, tests

- hcontext/doc.go
- hcontext/example_test.go
- hcontext/requestid.go
- hcontext/requestid_test.go
> hcontext: Add documentation, examples, tests

- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/sample.go
This can cause pages to not self resolve if we don't emit the 0s.
> Remove used concept for now

- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/sample.go
> Revert "Remove used concept for now"

- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/sample.go
> Revert "Revert "Remove used concept for now""

- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/report.go
With debug enabled, reported errors from the Librato package include the
full request sent to Librato, including headers. The errors also include
the response body -- but not the response headers.
The response headers are helpful for debugging failed requests, as well,
like for narrowing down the source of a rejected request.
This updates the `Body` of error responses to include the (scrubbed)
headers of the response as well as the text of the body.
> librato: include response headers in error

- tlsconfig/tlsconfig.go
Adds modern, legacy, and strict cipher selection. Useful for some canned
set of good defaults
> tlsconfig: add preconfigured ciphers

- tickgroup/README.md
We want to document the packages in `x/`.
* Add a README with an overview and an example
> tickgroup: add initial readme

- .golangci.yml
There are some exceptions, see the individual commits.
> Enable dupl, gosec, scopelint, nakedret, & gochecknoinits

- grpc/grpcclient/dial.go
This was removed in #77 and is needed by runtime.
@cyx: heads up in case this was removed on purpose.
> grpc: Re-adding Request-ID middleware

- .golangci.yml
- testing/mustcert/README.md
- testing/mustcert/example_test.go
Adds a godoc example for mustcert
> Add mustcert doc

- testing/mustcert/cert.go
Was looking at the godocs and realized I forgot to add the synopsis for mustcert
> update description of mustcert

- nacl/secretbox.go
- nacl/secretbox_test.go
Copy to mirror https://github.com/heroku/runtime/pull/4473
> nacl: Verify minimum length for message to decrypt

- hmiddleware/logger.go
- hmiddleware/logger_test.go
* Pulled from https://github.com/heroku/runtime/blob/fad8ed0baa88b7bf86a4888cbabc4256c50886be/lib/middleware/logger_test.go
* We are going to use this in Lyra Identity soon and I saw that pulling
this into X was previously suggested when the same code was added to the
Identity prototype https://github.com/heroku/lyra-labs/pull/208/files#r343058787
> Add logger middleware

- SECURITY.md
Adding security policy that is in alignment with other Salesforce repos.
> Creating Security Policy

- .github/workflows/codeql-analysis.yml
Setting up Action to enable Security Code scanning on the repo.
> Creating Code-QL Scanning

- README.md
Adding the status badge for the new Action defined for security code scanning.
> Adding code scanning Status Badge

- tlsconfig/tlsconfig.go
Added the SFCiphers list and SFAllowed function, which provides the TLS configuration allowed according to SFSS-151.
See https://help.salesforce.com/articleView?id=000351980
> Added salesforce allowed TLS ciphersuites

- cmdutil/metrics/otel/config.go
- cmdutil/metrics/otel/otel.go
Oops. The package name should be `otel`.
> Fix package name

- cmdutil/redispool/redispool.go
For Heroku Redis, we need to strip the username from the URL. After the release of Redis 6, clients began to support the new AUTH command that uses 2 arguments. Heroku Redis removed the `h` username from connection URLs, but only on new addons. Existing addons do not have the `h` removed so we must check for and remove it here.
See https://devcenter.heroku.com/changelog-items/1932
> deal with Redis 4, 5 & 6 compatibility issues

- .github/dependabot.yml
Adding dependabot.yml for our scanners to pick up the data
W-17033256
> add dependabot.yml config
