heroku/x

- go-kit/metrics/provider/librato/librato.go
After chatting with librato folks, it appears they recommend using
gauges for everything.
This PR changes the counters to be submitted as gauges.
> submit counters as gauges

- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
After trying out the current approach, it appears it's more work
since it will require you to derive every single chart metric.
Doing a reset on the counter simplifies a lot of this.
> counters: value reset every submission

- go-kit/metrics/provider/librato/librato.go
Certain projects use a single source for many dynos. This posting style requires SSA enabled for all metrics. To avoid having to manually enable SSA for new metrics created, it's easier to make this automatic.
- add `WithSSA` option
- submits a payload like the following if enabled:
```
curl -u $LIBRATO_USERNAME:$LIBRATO_TOKEN -H "Content-Type: application/json" -d '{
"source": "xyz.foobarbaz",
"gauges": [{
"name": "xyz.foobarbaz.gauge1",
"period": 60,
"min": 1,
"max": 1,
"sum": 1,
"sum_squares": 1,
"count": 1
}], "attributes": { "aggregate": true }
}' -X POST 'https://metrics-api.librato.com/v1/metrics' -i
```
> ssa enabled: all metrics are submitted with SSA

- hmetrics/example/advanced/main.go
- hmetrics/init.go
This simplifies the error reporting with an error handler letting
the user determine how to best handle the error.
Returning an error from the error handler abort metrics reporting
as well, giving the user an escape valve.
Additionally make the sharing of stats with ReadMemStats explicit.
> hmetrics: Simplify error reporting and other cleanups

- hmetrics/init.go
Also, I'm not sure calculating the derivative for pause times is the right thing to do here.
We don't do the same thing with the number of GC runs.
> hmetrics: Other metrics I think we should report

- hmetrics/hmetrics.go
For the purposes of testing, we often need to override the value of HEROKU_METRICS_URL, rewriting it to something specific for test. This provides a mechanism to make that change without compromising on the signature of `Report`.
> Configurable endpoint for hmetrics

- LICENSE.txt
- hmetrics/doc.go
- hmetrics/example/advanced/main.go
- hmetrics/example/basic/main.go
- hmetrics/example/onload/main.go
- hmetrics/examples_test.go
- hmetrics/hmetrics.go
- hmetrics/hmetrics_test.go
- hmetrics/onload/README.md
- hmetrics/onload/init.go
Document everything more, including usage of all exported bits.
Reduce the use of global variables down to the started flag and it's mutex.
Report is now synchronous, pushing that off to the caller if they directly use
Report. onload is unaffected. Cleaned up examples to reflect this.
Fixed the package name declaration in onload (was onloads by accident).
Renamed a few functions and variables for clarity.
> A bunch of cleanups; see comments

- hmetrics/onload/init.go
Currently package `hmetrics` in the `onload` configuration ignores all errors instead of logging them. This can make debugging of metrics collection errors very difficult and time-consuming. This patch offers a middle path between every error always being logged by default and no errors being logged. When the user sets `HMETRICS_VERBOSE=1` in the environment, all errors will be logged when they happen.
```
As a user of package hmetrics in customer code
In order to better debug metrics collection errors
Given the user set HMETRICS_VERBOSE to 1
When there is a reporting error
Then the reporting error is printed to standard error
```
```
As a user of package hmetrics in customer code
In order to better debug metrics collection errors
Given the user set HMETRICS_VERBOSE to 0
When there is a …
```
> hmetrics/onload: spew metrics errors when HMETRICS_VERBOSE is set truthy

- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/report.go
As part of doing our HTTP availability work in @heroku/runtime-tbd we've begun to explore the possibility of using a librato account with tags.
In order to start supporting tags, we'll want to change the semantics of `With(...)` to first of all:
1. Work
2. Register itself to something
Phase 1 is to just splat out the label values into the name using a convention, e.g. given:
```
prefix: heroku
name: http_request
tags: { region: us, app: myapp, space: myspace }
```
It computes to:
```
heroku.http_request.region:us.app:myapp.space:myspace
```
The next step is to separate out the reporter into 2 concrete interfaces with the same interface. A v1 and a v2 which will be switched to v2 automatically when you do `WithTags`.
The interface is drastically different that it seems to warrant this, …
> tags: phase 1 support

- go-kit/metrics/hllcounter.go
- go-kit/metrics/provider/librato/batcher.go
- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/report.go
- go-kit/metrics/provider/librato/sample.go
- Move histogram.measures out since it's hard coded to pre-tags
- Adds new test for tag based stuff
> Batcher: extract out so we can build a different batcher

- go-kit/metrics/provider/librato/batcher.go
- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/sample.go
Previously, `histogramMeasures` wasn't removed properly. That
has been removed, but also fixed by adding the tags / attributes
in all relevant places -- and also added more table tests for
the scenario of tags vs no tags.
> metrics: cleanup and add more tests

- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
We previously added tags. That stab mistakenly applied the prefix over and over.
In addition to the fix, added some table tests to ensure this regression won't happen.
> BUGFIX: fix over prefixing

- go-kit/metrics/provider/librato/batcher.go
- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
Combine the `batcher` types into a single struct type with a `batchMetrics` for tagless and `batchMeasurements` for tagged metrics.
Add tag arguments to the `librato.WithTags` opt func. Tags specified in the `WithTags` call are included in all metrics created by the provider.
> go-kit/metrics/provider/librato: combine batcher types, add default tags

- go-kit/metrics/provider/librato/batcher.go
- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/sample.go
Ignore unused (unobserved) metrics, which happens when an observer is only used to create tagged observers via `.With` method calls. Remove the `tagsEnabled` field from `batcher`, which was breaking tagging as it never was set. Use the `metricName()` helper to construct `Gauge` and `Counter` metric names.
>  go-kit/metrics/provider/librato: fix tagged histogram metric name, only sample used metrics

- go-kit/metrics/hllcounter.go
- go-kit/metrics/hllcounter_test.go
Swap the zero size cap for the len argument to avoid a panic when cap is zero.
> go-kit/metrics: fix zero cap panic in HLLCounter.With

- go-kit/metrics/provider/librato/batcher.go
- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/report.go
- go-kit/metrics/provider/librato/sample.go
Add a `librato.CardinalityCounter` struct that wraps the `(github.com/heroku/x/go-kit/metrics).HLLCounter` type. The wrapper type tracks usage to avoid submitting unused metrics, and handles tags added via `With` method calls.
>  go-kit/metrics/provider/librato: add CardinalityCounter wrapper type

- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/report.go
- go-kit/metrics/provider/librato/sample.go
We want internal metrics to be reported. For now, these are limited to:
1. The rate limits we're seeing
2. The total measurements sampled during reporting.
These measurements will allow us to monitor the provider itself (e.g. are we sending too many measurements) and potentially build alerts around them.
Connects to https://github.com/heroku/cedar/issues/2479
> Librato: add internal metrics

- go-kit/metrics/provider/librato/librato_test.go
- go-kit/metrics/provider/librato/report.go
We've observed in our systems that retries never succeed, but instead
always return a `401 Unauthorized` after the failure.
It turns out when using both WithRetries and WithRequestDebugging the
authentication was being dropped before retry attempts were made.
This updates the reporter to preserve headers when capturing debug
information so that subsequent retries can succeed.
> librato: fix authentication with retry and debug enabled

- go.mod
- hredis/redigo/redigo.go
Addresses the non-controversial change from #34  that got killed when I closed that pr.
> get rid of garyburd redigo in favor of gomodule: fixes #32

- grpc/grpcclient/dial.go
- grpc/grpchttp/request_id.go
- grpc/requestid/requestid.go
- grpc/requestid/requestid_test.go
- requestid/requestid.go
- requestid/requestid_test.go
- Request IDs come in as header `X-Request-ID` and `Request-ID`. Added a method to handle both.
- Updated RequestIDAnnotator to use `requestid.Get` instead of looking for a single Request ID header.
- Added AppendToOutgoingContext to read the Request ID from the context and append it to gRPC's outgoing.
- Added AppendOutgoingRequestID gRPC client interceptor which uses AppendToOutgoingContext
> Forward request ids

- testing/testenv/testenv.go
Currently it was pointed to be a bit paranoid and try and avoid any
local installs.
While that's great for certain setups, that's not a good default for a
typical simple setup as well.
These new defaults allow a docker setup still, but also works well with
a typical brew install of redis / postgres.
> testenv: improvements on defaults

- go.sum
- hmiddleware/acm.go
- hmiddleware/acm_test.go
This middleware is useful for implementing the heroku ACM specific
contract for redirecting to the origin ACM servers.
Customers shouldn't need to use this if they're just leveraging the
platform normally -- but is more for fringe cases.
> hmiddleware: add acm

- go.mod
- tickgroup/tickgroup.go
- tickgroup/tickgroup_test.go
Tickgroup is useful in cases where you want a clock process that takes
action every N seconds.
In certain cases, you'd want them ticking at different rates, or even
have multiple tickgroups orchestrated on a higher level.
> add tickgroup

- healthcheck/tcpserver.go
- healthcheck/tcpserver_test.go
Provides a simple TCP server which has metrics baked in, useful for
responding to ELB health checks or other forms of generic TCP based
health checks in general.
> add healthcheck package

- go.sum
- grpc/grpcserver/options.go
In order to use https://github.com/mwitkow/go-proto-validators you need to register the proper middleware with the core server. This enables a user to do that using our middleware wrappers
* Adds new interceptor to grpcserver package
> Adds ValidateInterceptor for go-proto-validators

- tickgroup/README.md
- tickgroup/example_test.go
- tickgroup/tickgroup.go
Per feedback in #85, moving documentation for `tickgroup` to godoc.
> tickgroup: move docs to godoc

- go-kit/metrics/testmetrics/provider.go
- hmiddleware/httpmetrics/httpmetrics_test.go
This adds an example for the godocs of `httpmetrics`.
> Add example for httpmetrics

- go.mod
- go.sum
- grpc/grpcserver/options.go
It seems at some point this repo was renamed. v1.1.0 adds a go.mod
file which sets the module path as
`github.com/grpc-ecosystem/go-grpc-middleware` which causes trouble
along with the old import path.
> grpc/grpcserver: use canonical import path

- cmdutil/oc/open_census.go
- cmdutil/server.go
- cmdutil/server_test.go
ocagent.Exporter.Start() returns immediately, which violates oklog/run.Group semantics, so use NewContextServer instead to block until something else brings down the Group.
Also updated the documentation for the various Server types and created some rudimentary examples in hopes that future readers won't fall into the same traps that I did.
> Fix OC Agent / document cmdutil.Server and related / add examples.

- grpc/grpcclient/h2c.go
- grpc/h2c_e2e_test.go
- hmiddleware/basicauth/grpc_test.go
DialH2C used many deprecated features so I deprecated DialH2C and provided DialH2CContext which takes a context argument and is current with existing gRPC implementation.
> Added new gRPC DialH2CContext function to supplant DialH2C

- hmiddleware/basicauth/checker.go
- hmiddleware/basicauth/checker_test.go
String comparison can be susceptible to side-channel attacks.
Use constant time string comparison.
> basicauth: Use constant time comparison in checker

- cmdutil/redispool/redispool.go
We have seen leaking connection counts when missing to close redis  connections after `Get` from a pool. The redigo pool supports a `MaxConnLifetime` config 
(see https://github.com/gomodule/redigo/blob/master/redis/pool.go#L160-L162) which when set to non zero automatically closes connections older than the set duration.
Here we introduce a new environment variable `REDIS_MAX_CONN_LIFETIME` which defaults to `0s` to retain the original behaviour.
> redispool: Add optional config to set max conn lifetime

- cmdutil/oc/open_census.go
- cmdutil/service/standard.go
This provides and escape value from the coded intent to enable open
census tracing.
> Disable starting exporter if OC_AGENT_ADDR isn't set.

- hmiddleware/httpmetrics/doc.go
- hmiddleware/httpmetrics/example_test.go
- hmiddleware/httpmetrics/httpmetrics.go
- hmiddleware/httpmetrics/httpmetrics_test.go
The httpmetrics package was confusing and awkward to use:
1. It's only exported method was `NewServer`, which actually returned
an `http.Handler`.
2. It did not conform to standard middleware function signature, so it
required every user to wrap in another function to use it.
This deprecates `NewServer` in favor of `New(metrics.Provider)` which
returns a normal middleware constructor. This means users can do:
```go
router.Use(httpmetrics.New(svc.MetricsProvider))
```
instead of 
```go
router.Use(func(next http.Handler) http.Handler {
return httpmetrics.NewServer(svc.MetricsProvider, next)
})
```
It also moves the example into a `httpmetrics_test` package so that the
example code uses correct package names and is easier to drop into real code.
> httpmetrics: provide standard middleware entrypoint

- cleanurl/cleanurl.go
- cmdutil/debug/debug.go
- cmdutil/health/serve.go
- cmdutil/server.go
There are a number of packages with no package documentation at the
moment, which can make it challenging to navigate the repo if you don't
already know what's there.
This adds some package docs for a few that were missing it,
working mostly alphabetically through the first few packages
at https://godoc.org/github.com/heroku/x#pkg-subdirectories.
> Add some package documentation

- hcontext/requestid.go
- hcontext/requestid_test.go
* If there is a X-Request-Id header, it was being added to the context but
not the headers
* Headers are what gets logged by the request_logger middleware so
adding to headers is helpful for logging/splunking
* https://gus.my.salesforce.com/a07B00000078HcyIAE
> Add appended request_id to headers

- go.mod
- go.sum
We had originally pointed at master for #123, though it has since been
tagged at v1.2.0: https://github.com/grpc-ecosystem/go-grpc-middleware/issues/259
/cc @bernerdschaefer
> Update go-grpc-middleware to v1.2.0

- cmdutil/service/standard_http_test.go
- cmdutil/signals/signals_test.go
- grpc/panichandler/panichandler_test.go
- hmiddleware/basicauth/grpc_test.go
- hmiddleware/logger_test.go
- hmiddleware/request_logger_test.go
- testing/testlog/example_test.go
- testing/testlog/testlog.go
The testlog package's function to get a test logger was `NewNullLogger`,
which was used to match the function name in logrus' hook test package.
Most folks using this package now, however, have not used the logrus
package, and there are no other kinds of test loggers in the package, so
using `New` instead reads better.
This also documents the package and adds examples.
> testing/testlog: add New function

- go.mod
- go.sum
Includes fix to silence error on shutdown.
Pulls in https://github.com/google/gops/pull/97 until it gets released. Full changes: https://github.com/google/gops/compare/v0.3.7...3a98d6d24562.
> go.mod: bump gops to 3a98d6d24562

- logplex/encoding/encoder.go
- logplex/encoding/encoder_test.go
Make our Go timestamp encoding like Logplex (erlang), padding seconds up to 6 places.
Before
```
2020-03-10T15:36:08.21395+00:00 app[publish.1]: time="2020-03-10T15:36:08Z" level=info msg="report tick"
2020-03-10T15:36:09.213969+00:00 app[publish.1]: time="2020-03-10T15:36:09Z" level=info msg="report tick"
```
After
```
2020-03-10T15:36:08.213950+00:00 app[publish.1]: time="2020-03-10T15:36:08Z" level=info msg="report tick"
2020-03-10T15:36:09.213969+00:00 app[publish.1]: time="2020-03-10T15:36:09Z" level=info msg="report tick"
```
> logplex/encoding: timestamp padding

- cmdutil/https/config.go
- cmdutil/https/serve.go
Adding Read and Write timeout properties. These values can serve as failsafes should the component's load balancer i.e ELB no longer implement timeouts for some reason. This is a defence-in-depth measure.
> Adding Timeout Configs to config.go

- go.mod
- go.sum
Hey 👋 
i just discovered that the redigo versioning seems off. If you check the GitHub page https://github.com/gomodule/redigo/tags and https://github.com/gomodule/redigo/releases you can see that 1.8 is the latest release and that the 2.0 tag is several years old.
In numbers this is a "downgrade" but in reality this is now using a go modules compatible and more recent version.
> Use Redigo 1.8 as it's the latest release

- logplex/encoding/encoder.go
- logplex/encoding/encoder_test.go
@freeformz was so kind to point out room for improvement here. Use `strings.Builder` instead of `fmt.Sprintf` to format logplex messages.
> logplex/encoding: Improve encoding performance

- logplex/encoding/scanner.go
Requiring a ReadCloser is unnecessary since nothing in the encoding
process needs to call Close.
> logplex/encoding: NewDrainScanner takes a Reader

- go.mod
- go.sum
- hmiddleware/request_logger.go
- hmiddleware/request_logger_test.go
v0.2.0 of rollrus updates error reporting to be async for non-panic and
fatal errors.
v4.1.0 of chi introduced a breaking change to the middleware.LogEntry
interface, so users of heroku/x were forced to lock to the 4.0.x series.
> Bump chi and rollrus versions

- .circleci/config.yml
- cmdutil/service/standard.go
- cmdutil/service/standard_test.go
- go-kit/metrics/provider/librato/librato.go
envdecode requires that at least one field in a provided config struct
match from the environment. This sometimes makes the standard service
awkward to work with, particularly when gradually migrating an existing
system.
It's common to see this while getting started:
```go
var cfg struct {
AppName string `env:"APP_NAME"` // mirror APP_NAME from svclog for envdecode
}
s := service.New(&cfg)
```
This updates `service.New` to accept nil for for the appConfig argument
to ease conversion of services.
> cmdutil/service: support service.New(nil)

- cmdutil/svclog/logger.go
- cmdutil/svclog/logger_test.go
I've noticed a number of cases where a logger might not be given so null logger is used. I figured it would be helpful to centralize the pattern.
> Add Helpers for 'Null Logger'

- tlsconfig/tlsconfig.go
Adding ECDSA ciphers to the SF ciphers list to account for customers with EC certs. Per conversations with security, adding CHACHA variants and removing CBC variants while we're here. (And fixing an unrelated compiler warning re: casting `x509.PublicKeyAlgorithm` to a string instead of using its String func.)
> Add ECDSA and CHACHA, remove CBC

- go-kit/metrics/provider/librato/batcher.go
[This document](https://salesforce.quip.com/TOdVAy7RPs4R#ANJACAaoKDw) describes using query parameters on Librato API and l2met URLs to control routing of metrics through an OpenTelemetry collector.
Unfortunately, `heroku/x/go-kit` currently removes query parameters from the Librato URL [here](https://github.com/heroku/x/blob/023c823c2229dd9af1acbd354c0ea7758768df40/go-kit/metrics/provider/librato/batcher.go#L45). You can see a `go-playground` demonstration of the problem [here](https://play.golang.org/p/OzGHe1RkvVj).
This pull request copies `RawQuery` from the original URL to the new URL, to preserve query parameters.
Reference: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000BiXTYA0/view
> Preserve query parameters when sending data to librato

- logplex/encoding/parser.go
- logplex/encoding/scanner.go
- logplex/encoding/scanner_test.go
The `hermes` router will emit the `path` as part of the router log lines. This field is unbounded causing the entire logline to be unbounded. Typically, on the platform where log-shuttle is used, it will wrap loglines at the 10k boundary mark. We have put `hermes` into hard maintenance mode and are not planning to release any changes to `hermes`.
These additional config options will allow customization in `logfwd` to handle these longer log lines in a handful of ways.
- Added option functions to control Buffer and Split on the scanner.
- Added a truncating parser.
- [Page](https://heroku.slack.com/archives/CCKDFGTL7/p1623918657158900)
- [Incident 2292](https://heroku.slack.com/archives/C025R2PV5H7/p1623928500000200)
- [SOX](https://heroku.slack.com/archives/C01D8TPMKPB/p1623946428183300)
> Give more control over the scanner to the enduser

- go.mod
- go.sum
`heroku-otel-collector` does not compile locally on mac. The error looks like this:
```
~/git/heroku-otel-collector/collector/src main
❯ go build ./...
/usr/local/Cellar/go/1.16.2/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
duplicate symbol '_readdrivestat' in:
/var/folders/9s/s_b3dc1j7wldkn1gmyr74zw80000gp/T/go-link-822498051/000007.o
/var/folders/9s/s_b3dc1j7wldkn1gmyr74zw80000gp/T/go-link-822498051/000034.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Investigation with `go mod graph` reveals:
* github.com/google/gops@v0.3.8-0.20200229223415-3a98d6d24562 github.com/shirou/gopsutil@v0.0.0-20180427012116-c95755e4bcd7 <-- shirou/gopsutil is pulled in by google/gops.
* …
> Update google/gops in order to update gopsutil

- cmdutil/metrics/metrics.go
This puts the `otel.Config` as a field on the general `metrics.Config`.
> Include the otel config as part of general metrics config

- cmdutil/redispool/redispool.go
Connect to any Heroku Redis plan using Redis 6 (default) require TLS (see https://devcenter.heroku.com/articles/heroku-redis#security-and-compliance).
This commit follows the directions outlined in [Connecting to Go](https://devcenter.heroku.com/articles/heroku-redis#connecting-in-go) to allow for both TLS and non-TLS connections.
> Add support for Heroku Redis 6 using TLS

- cmdutil/metrics/otel/otel.go
- go-kit/metrics/l2met/l2met.go
- go-kit/metrics/multiprovider/multiprovider.go
- go-kit/metrics/provider.go
- go-kit/metrics/provider/discard/discard.go
- go-kit/metrics/provider/librato/librato.go
- go-kit/metrics/provider/otel/provider.go
- go-kit/metrics/testmetrics/provider.go
- go.mod
- go.sum
- lambda/function.go
- lambda/function_test.go
This addition includes a utility package that can be used to standardize the configuration and handler set-up of our Lambda functions. It is modeled off of the `cmdutil.Service` type.
The go-kit `metrics.Provider` interface has been extended to include a `Flush()` method that operates much the same as `Stop()`, but does not tear down the provider and may be called multiple times. In some cases, `Flush()` is a no-op. It has been added here so that recorded metric values may be optionally flushed to the provider service from within the handler. This has proved necessary when using the Librato & OTEL providers, to ensure data are not lost when the execution context of the Lambda invocation is torn down.
> Add utils for setting up lambda handlers

- sharder/sharder.go
- sharder/sharder_test.go
This change adds complete control over the hashing algorithm used by the
Sharder. Sometimes a user may want to tightly control allocations, other
times a user may just want pure concurrency.
The existing behavior remains unchanged so that existing users of the
library are not surprised. This existing behavior is now wrapped as the
`WithLockingHasher` option.
A second option, `WithLockFreeHasher` is available that uses the
same fnv hashing algorithm without the use of locks.
A third option, `WithHasher`, allows for complete customization.
> adds ability to choose the hash used for sharding

- sharder/sharder.go
#161 switched the hashing algorithm from fnv32a to fnv32. Reverting that change.
> back to fnv32a for hashing

- go-kit/metrics/provider/otel/provider.go
Some of our alerting for our Runtime services will rely on percentage-based metrics computed using other simple metrics. Each percentage-based metric is computed over a single event, so numbers can fluctuate widely when the underlying metrics are `undefined`. Collecting the metrics at a lower frequency (less often) will ensure more of the underlying metrics are defined on the events, making the derived column value more accurate and meaningful. 
- Hard-code the `CollectPeriod` to be `1m` on the OTEL controller.
> Collect OTEL metric data once a min

- cmdutil/metrics/otel/otel.go
- go-kit/metrics/provider/otel/client.go
[Buzz](https://github.com/heroku/buzz) needs to be able to configure multiple providers multiple times as a part of its operational approach. The existing code works the first time a provider is initiated, but if it is attempted a second time, it fails. 
The `collectorURL` is passed in by reference, and the code inside the method mutates the URL; no bueno. This change passes the URL by value, so the mutation has no base side effects.
> Pass collector URL by value

- go-kit/metrics/provider/otel/options.go
- go-kit/metrics/provider/otel/provider.go
This will remove the hard-coding of `CollectPeriod = 1m` and allow for the caller to configure the period via an option to `xotel.New(...)`.
> Provide opt to config OTEL provider collect period

- grpc/grpcmetrics/highcardmetrics/server.go
- grpc/grpcmetrics/highcardmetrics/server_test.go
- grpc/grpcserver/options.go
We want to add two new options to the grpc server, which allows us to collect metrics using attributes. 
The new `highcardmetrics` pkg provides high cardinality unary and stream server interceptors. The interceptors take an `explicit` bool arg, which makes the histogram type configurable. Passing in `true` will create explicit histograms with a default 5s distribution. 
To initialize a grpc server with high cardinality unary and stream servers using explicit histograms:
```go
gSrv, hSrv := grpcserver.NewStandardH2C(
apiSrv,
// high cardinality interceptors using explicit histograms
grpcserver.HighCardInterceptors(
highcardmetrics.NewUnaryServerInterceptor(o.metricsProvider, true), 
highcardmetrics.NewStreamServerInterceptor(o.metricsProvider, true),
),
)
```
> add new highcardmetrics pkg to grpcmetrics

- go-kit/metrics/provider/otel/provider.go
The call to otel provider's `gauge.Add()` erroneously calls `gauge.Set()`. 
This PR fixes the bug, by calling `gauge.Add()`.
> go-kit: fix gauge bug in otel provider

- .circleci/config.yml
- cmdutil/spaceca/spaceca.go
- go-kit/metrics/provider/librato/librato_test.go
- hmetrics/example/advanced/main.go
- hmetrics/examples_test.go
The go.mod file in this repository specifies that we're relying on Go 1.15 yet the CircleCI configuration used older versions.
This uses Go 1.15 for test runs and for linting (by upgrading to the [golangci/golangci-lint@v1.31.0](https://github.com/golangci/golangci-lint/releases/tag/v1.31.0) release).
A couple changes were made to satisfy the later version of `golangci-lint`.
> Use consistent Go version

- cmdutil/redispool/redispool.go
- go-kit/metrics/distributions.go
- go.mod
- go.sum
A couple of quick enhancements.
- Updated redigo dependency.
- Converted the `redispool` wrapper to use `DialContext` over `Dial` to allow for proper propagation of contexts that may have deadlines or otherwise be cancelled.
- Added a TenSecondDistribution to provide a middle between the 5s and 30s distributions for time based histograms.
> Quick enhancements to redispool and available histogram distributions

- cmdutil/redispool/redispool.go
Calls to redigo's `pool.Get()` will only block when configured to do so. The default behaviour will simply return instead of waiting (see https://github.com/gomodule/redigo/blob/master/redis/pool.go#L154-L156).
This PR introduces extra configuration to allow customization of this behaviour.
> allow redigo pools to wait

- go-kit/metrics/lowcard/low_cardinality.go
- go-kit/metrics/lowcard/low_cardinality_test.go
This PR adds a `lowcard` package that may be used to wrap `metrics.Provider`s. 
Labels added to instruments using `With()` will be ignored unless explicitly marked for inclusion. Label inclusion is indicated by passing the list to `NewLowCardinalityWrappedProvider()` as an argument when creating the low card wrapper.
> Add low card provider for optionally skipping labels

- cmdutil/metrics/metrics.go
- cmdutil/service/standard.go
We don't want to run an `l2met` provider by default. With a [prior change](https://github.com/heroku/x/pull/179/files#diff-9692d64d304dc9da6aaa7ad1bac87402306ed56bb5507e9665598bc9e0f7b997L76-R77), that is now the behavior.
This PR changes the default behavior so that an `l2met` provider will only be started if OTEL is not enabled. This behavior can be overridden by setting the `METRICS_ENABLE_L2MET_OVERRIDE` env var, in which case, an `l2met` provider will be started regardless of the OTEL settings.
> Only start l2met provider when OTEL not enabled

- cmdutil/service/standard.go
When `service.Run()` exits, it's possible to panic because `MetricsProvider` may be `nil`.
In the future, we should perhaps set-up an OTEL provider or a NOOP provider by default.
> Check if MetricsProvider is nil, avoid panics

- cmdutil/metrics/metrics.go
- cmdutil/metrics/metrics_test.go
- cmdutil/rollbar/rollbar.go
- cmdutil/rollbar/rollbar_test.go
- cmdutil/service/integration_test.go
- cmdutil/service/standard.go
- cmdutil/service/standard_test.go
- cmdutil/svclog/logger.go
- cmdutil/svclog/logger_test.go
- go-kit/metrics/l2met/l2met.go
- lambda/function.go
We'd like to see a metric when we see panics in a standard service.
* Add `ReportPanic` function to `cmdutil/metrics` that creates a counter `panic` on the metrics provider configured with a service.
* Move `ReportPanic` logging function to `cmdutil/svclog`
* L2met metrics provider now logs on `Flush`
* Add integration test that shows logs on a service panic for l2met and standard logger
* [W-13145387](https://gus.lightning.force.com/a07EE00001QhRMcYAN)
> cmdutil/service: improve panic reporting

- hmiddleware/httpmetrics/httpmetrics.go
- hmiddleware/httpmetrics/httpmetrics_v2.go
- hmiddleware/httpmetrics/httpmetrics_v2_test.go
Here we add a option to improve HTTP metrics reporting with OTEL.
* Add `NewV2` function to `httpmetrics` which uses attributes over metric names
[W-13781478](https://gus.lightning.force.com/a07EE00001WSFXiYAP)
> Make httpmetris work better with OTEL

- go-kit/metrics/testmetrics/metrics.go
- go-kit/metrics/testmetrics/provider.go
**Reasons For the Change:** 
While we are using testmetrics pkg in one of our unit tests, we observed `CheckCardinalityCounter` is not working as expected. 
Inside the `Provider` of testmetrics, all the counters we are using, are of `metrics.go` except for `cardCounters`. For `cardCounters` we are using `xmetrics.HLLCounter`. We weren't adding labels properly and `CheckCardinalityCounter` was not taking `labelValues`. Also all the counters of `metrics.go` are having `Provider` of testmetrics which is not for   `xmetrics.HLLCounter`. We wanted to add new `CardinalityCounter` inside `metrics.go` of testmetrics that has `Provider` inside it and adds, checks for labels correctly. 
**Changes:** 
- Added CardinalityCounter which implements CardinalityCounter interface of go-kit/metrics
- …
> Add CardinalityCounter to testmertics

- go-kit/metrics/testmetrics/metrics.go
- go-kit/metrics/testmetrics/provider.go
**Reason For the Change:** 
While using testmetrics provider in the testcases, we observed CheckObservation is failing when we don't add anything inside the Histogram. 
When we are sending an empty float64 list:  `empty := float64[]` to CheckObservation, it was failing .  
The reason is, we are not initializing observations in the newHistogram function of the testmetrics provider. 
**Changes:** 
Initializing the observations of Histogram in newHistogram function.
> Update newHistogram of testmetrics Provider

- go-kit/metrics/provider/otel/options.go
Discovered that services using latest version of OTEL utilities from `x` would get authorization failures sending metrics to OTEL collectors that required auth.  Tracked down this bug.
> Properly construct auth header for OTEL Metric endpoints

- dynoid/dynoidtest/dynoidtest.go
This uses `http.ServeMux` for the `dynoidtest` package. There is no need for it to take a dependency on something else.
> Prefer built-in multiplexer

- go-kit/metrics/provider/otel/provider.go
- go-kit/metrics/provider/otel/types.go
Currently, the `otel.Provider` uses a `sync.Mutex` to protect against race conditions on the maps that store instances of the different metric types. The mutex blocks to ensure the existence of a metric on metric modification. 
We can avoid fully blocking on reads for already existing metrics with a `sync.RWMutex`.
> Use RWMutex in OTEL provider

- cmdutil/debug/debug.go
- cmdutil/debug/debug_test.go
- cmdutil/server.go
**Description**
We want to configure the pprof listener that is capable of running mutex profiles on server set-up in `cmdutil/debug`. This PR created a new `NewPprofServer` method to the `cmdutil/debug` package, allowing for the setup of a `pprof` server with configurable profiling types and optional mutex profiling. 
**Changes**
- Add `PProfServerConfig` struct: holds configuration for the pprof server.
- Add `PProfServer` struct: wraps a pprof server
- Implement `NewPProfServer` function: creates and configures the pprof server.
- Implement `Run` and `Stop` methods: the `NewPProfServer` function includes `Run` and `Stop` methods for managing the pprof server lifecycle.
- Write unit tests for `NewPProfServer`
**Metadata**
[W-16252388](https://gus.lightning.force.com/lightning/r/ADM_Work_ …
> Set up a pprof server with optional mutex profiling in cmdutil

- cmdutil/debug/config.go
- cmdutil/debug/debug.go
- cmdutil/debug/debug_test.go
- cmdutil/service/standard.go
**Description**
We want to start the PProf debug server from Standard based on a config
**Changes**
- Updated debug config
- updated NewPProf Server
- Updated standard to start PProf based on EnablePprofDebugging config
**Metadata**
[W-16499473](https://gus.lightning.force.com/a07EE00001z1VZ9YAM)
> Refactor and Start PProf debug server

- go-kit/metrics/testmetrics/provider.go
Adding a `CheckCounterExists` function to `testmetrics` would be helpful for scenarios where we need to verify that a metric exists and is not 0, but we can't determine the exact counter value.
> go-kit: Add CheckCounterExists for testmetrics

- cmdutil/server.go
Currently we are not having an option to add a stop function for Context Server. With this addition you can add different stopFunction that can be executed when the server is stopping.
- added stopFunc ...func(error) argument to NewContextServer
> Add custom stop function to Server

- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- README.md
- go.mod
Update to the latest version of the codeql action to get updated scanners.
- Update action to `v3`.
- Update `go.mod` to conform to the go `x.y.z` version.
- Always run codeql when a PR is merged.
- [v2 Release](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/)
- [v3 Release](https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/)
> Update CodeQL to v3
